
export const ALL_POKEMONS = 'ALL_POKEMONS';
export const CLEAN_ALL_POKEMONS = 'CLEAN_ALL_POKEMONS';
export const ALL_TYPES = 'ALL_TYPES';
export const CLEAN_ALL_TYPES ='CLEAN_ALL_TYPES';
export const POKEMON_BY_ID = 'POKEMON_BY_ID';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME';
export const CLEAN_POKEMON_NAME = 'CLEAN_POKEMON_NAME';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_ATTK = 'ORDER_BY_ATTK';
export const FILTER_TYPE = 'FILTER_TYPE';
export const FILTER_DB_API = 'FILTER_DB_API';
export const POST_POKEMON = 'POST_POKEMON';